import type { KeywordTier } from './types'

export const DEFAULT_HOOK_TIERS_TH: KeywordTier[] = [
  {
    tier: 1,
    weight: 25,
    keywords: [
      'ด่วน',
      'วันนี้เท่านั้น',
      'จำกัด',
      'หมดแล้ว',
      'ล็อตสุดท้าย',
      'เกือบหมด',
      'เหลือน้อย',
      'หมด',
      'ปิดโปร',
      'โปรสุดท้าย',
      'ชิ้นสุดท้าย',
      'สต็อกจำกัด',
      'เหลือไม่กี่ชิ้น',
      'รีบเลย',
      'นาทีนี้',
    ],
  },
  {
    tier: 2,
    weight: 15,
    keywords: [
      'ลด',
      'โปร',
      'ฟรี',
      'ส่งฟรี',
      'ของแถม',
      'ราคา',
      'เหลือ',
      'พิเศษ',
      'ราคาพิเศษ',
      'แถม',
      'ถูก',
      'คุ้ม',
      'ลดราคา',
      'ราคาพัง',
      'แฟลชเซล',
      'เซล',
      'โค้ด',
      'คูปอง',
      'ซื้อ 1 แถม 1',
      'ส่วนลด',
      'ราคาถูก',
    ],
  },
  {
    tier: 3,
    weight: 8,
    keywords: [
      'ไวรัล',
      'รีบ',
      'CF',
      'ตัวนี้',
      'ซื้อเลย',
      'โอนเลย',
      'หยิบเลย',
      'สั่งเลย',
      'จองเลย',
      'เอาไหม',
      'ใครเอา',
      'ขายดี',
      'ปัง',
      'กดเลย',
      'คอมเมนต์เลย',
      'ทักมา',
      'ต้องมี',
      'ดังมาก',
      'ฮิต',
      'แนะนำ',
      'ไลฟ์นี้',
      'วันนี้',
      'เพิ่มลงตะกร้า',
    ],
  },
]

export const DEFAULT_HOOK_TIERS_EN: KeywordTier[] = [
  {
    tier: 1,
    weight: 25,
    keywords: [
      'limited',
      'last chance',
      'almost gone',
      'selling out',
      'sold out',
      'ending soon',
      'hurry',
      'only left',
      'limited time',
      'running out',
      'going fast',
      'act now',
      "don't miss",
      'flash sale',
      'final',
      'clearance',
    ],
  },
  {
    tier: 2,
    weight: 15,
    keywords: [
      'discount',
      'promo',
      'free',
      'free shipping',
      'gift',
      'special',
      'deal',
      'offer',
      'save',
      'off',
      'sale',
      'coupon',
      'code',
      'bundle',
      'bogo',
      'price drop',
      'exclusive',
      'bonus',
      'cashback',
    ],
  },
  {
    tier: 3,
    weight: 8,
    keywords: [
      'buy now',
      'order now',
      'get it now',
      'grab it',
      'shop now',
      'add to cart',
      'trending',
      'viral',
      'best seller',
      'who wants',
      'comment below',
      'drop a',
      'dm me',
      'must have',
      'limited edition',
      'get yours',
      'claim',
      'sold',
      'how many',
    ],
  },
]
